/** Service catalogue modelled on the customer categories at app.padosipro.com. */

export const CATALOGUE = [
  {
    id: "errands",
    name: "Errands & Daily Tasks",
    blurb: "Bills, banks, documents, government work",
    icon: "file-text",
    soon: false,
    services: [
      ["pickups", "Pickups & Deliveries", "Couriers, documents, and things that need to move."],
      ["payments", "Payments & Renewals", "Bills, fees, and renewals paid on time."],
      ["docs-gov", "Documents & Government", "Forms, submissions, and government follow-ups."],
      ["shopping", "Shopping", "Errands and purchases handled for the household."],
    ],
  },
  {
    id: "home",
    name: "Home Services",
    blurb: "AC, plumbing, electrical, cleaning, repairs",
    icon: "home",
    soon: false,
    services: [
      ["cleaning", "Cleaning", "Deep cleans and regular house cleaning."],
      ["repairs", "Repairs", "Plumbing, electrical, and handyman repairs."],
      ["appliances", "Appliances & Utilities", "AC, gas, and appliance servicing."],
      ["property", "Property & Society", "Society work, inspections, and upkeep."],
    ],
  },
  {
    id: "travel",
    name: "Travel & Tourism",
    blurb: "Flights, hotels, visas, transfers, itineraries",
    icon: "map-pin",
    soon: false,
    services: [
      ["book-travel", "Book Travel", "Flights, hotels, and the plan for the trip."],
      ["on-trip", "On-Trip Support", "Changes, pickups, and help while you are away."],
      ["visa", "Documents & Visa", "Visa papers and travel documents."],
      ["local-transport", "Local Transport", "Cabs, drivers, and airport transfers."],
    ],
  },
  {
    id: "health",
    name: "Health & Medical",
    blurb: "Doctor visits, pharmacy, labs, physio",
    icon: "heart",
    soon: false,
    services: [
      ["appointments", "Appointments & Tests", "Doctor visits, labs, and pharmacy runs."],
      ["records", "Records & Reports", "Reports collected and kept in order."],
      ["hospital", "Hospital & Emergency", "Admissions and hospital coordination."],
      ["claims", "Insurance & Claims", "Claim paperwork and follow-ups."],
    ],
  },
  {
    id: "senior",
    name: "Senior Care",
    blurb: "Check-ins, medicines, vitals, companionship",
    icon: "users",
    soon: false,
    services: [
      ["daily-care", "Daily Care", "Check-ins, meals, and company at home."],
      ["medical-support", "Medical Support", "Medicines, vitals, and appointment days."],
      ["safety", "Safety & Mobility", "Fall safety, walks, and getting around."],
      ["family", "Family Coordination", "Updates shared with the family."],
    ],
  },
  {
    id: "events",
    name: "Events & Management",
    blurb: "Weddings, décor, catering, photography",
    icon: "calendar",
    soon: false,
    services: [
      ["planning", "Planning & Venue", "Dates, venues, and the run of show."],
      ["vendors", "Vendors & Services", "Décor, catering, and photography."],
      ["guests", "Guests", "Invites, stays, and guest logistics."],
      ["event-day", "Event Day & After", "The day itself, then the wrap-up."],
    ],
  },
  {
    id: "workforce",
    name: "Workforce Management",
    blurb: "Maids, cooks, drivers, nannies, payroll",
    icon: "briefcase",
    soon: false,
    services: [
      ["hire", "Hire Staff", "Maids, cooks, drivers, and nannies."],
      ["payroll", "Staff Records & Payroll", "Attendance, salary, and records."],
      ["verification", "Verification", "Background checks before someone starts."],
      ["replacement", "Replacement & Exit", "A replacement, or a clean exit."],
    ],
  },
  {
    id: "digital",
    name: "Digital & Tech Help",
    blurb: "WiFi, CCTV, smart locks, device repair",
    icon: "wifi",
    soon: false,
    services: [
      ["device-setup", "Device Setup", "Phones, TVs, and new devices ready to use."],
      ["internet", "Internet & Home Tech", "Wi-Fi, CCTV, and smart locks."],
      ["accounts", "Accounts & Data", "Email, backups, and account setup."],
      ["safety-support", "Safety & Support", "Repairs and help when something fails."],
    ],
  },
  {
    id: "relocation",
    name: "Relocation Services",
    blurb: "Packers, movers, handover, paperwork",
    icon: "package",
    soon: false,
    services: [
      ["find-home", "Find a Home", "Shortlists and visits for a new place."],
      ["move", "Move Execution", "Packers, movers, and the moving day."],
      ["setup-home", "Set Up New Home", "Utilities and the first week in a new home."],
      ["transfers", "Transfers & Paperwork", "Address changes and handover papers."],
    ],
  },
  {
    id: "nutrifix",
    name: "NutriFix",
    blurb: "Groceries, food delivery, diet plans, meal prep",
    icon: "coffee",
    soon: true,
    services: [
      ["diet", "Diet Plans", "A plan built around the household."],
      ["meals", "Meal Delivery", "Meals planned and delivered."],
      ["groceries", "Groceries", "A restock without the market run."],
      ["corporate", "Special & Corporate", "Events, fasting days, and office meals."],
    ],
  },
  {
    id: "fashion",
    name: "Fashion & Styling",
    blurb: "Salon at home, tailoring, styling, gifting",
    icon: "scissors",
    soon: true,
    services: [
      ["styling", "Styling", "Salon at home and personal styling."],
      ["tailoring", "Tailoring & Alterations", "Fittings, alterations, and pickups."],
      ["sourcing", "Sourcing", "Outfits, gifts, and accessories found for you."],
      ["garment", "Garment Care", "Laundry, repairs, and wardrobe care."],
    ],
  },
  {
    id: "religious",
    name: "Religious & Cultural",
    blurb: "Pandit booking, puja, temple visits",
    icon: "sun",
    soon: true,
    services: [
      ["pooja", "Pooja & Priest", "A pandit and the puja arranged."],
      ["festivals", "Festivals & Rituals", "Festival prep and ritual logistics."],
      ["materials", "Materials & Offerings", "Samagri and offerings sourced."],
      ["pilgrimage", "Pilgrimage & Community", "Temple visits and community events."],
    ],
  },
  {
    id: "business",
    name: "Business Support",
    blurb: "Registration, GST, bookkeeping, compliance",
    icon: "layers",
    soon: true,
    services: [
      ["company", "Company Setup", "Registration and the first filings."],
      ["tax", "Tax & Compliance", "GST, reminders, and compliance."],
      ["legal", "Documents & Legal", "Agreements, copies, and notarisation."],
      ["office", "Office Admin", "Bookkeeping and day-to-day admin."],
    ],
  },
  {
    id: "education",
    name: "Education Support",
    blurb: "Tutors, admissions, exam prep",
    icon: "book",
    soon: true,
    services: [
      ["tutors", "Tutors & Classes", "Tutors found and scheduled."],
      ["admissions", "Admissions", "Forms, visits, and admission follow-ups."],
      ["exams", "Exams & Forms", "Exam logistics and form filling."],
      ["courses", "Courses & Career", "Course enrolment and career logistics."],
    ],
  },
  {
    id: "insurance",
    name: "Insurance & Loans",
    blurb: "Compare policies, plan loans, paperwork handled",
    icon: "shield",
    soon: true,
    services: [
      ["health-insurance", "Health insurance", "Policies compared and paperwork handled."],
      ["life-insurance", "Life insurance", "A plan chosen and the forms filed."],
      ["vehicle-insurance", "Vehicle insurance", "Renewals and new cover arranged."],
      ["personal-loan", "Personal loan", "Options compared and the application run."],
      ["home-loan", "Home loan", "Paperwork and follow-ups for a home loan."],
    ],
  },
].map((category) => ({
  ...category,
  services: category.services.map(([id, name, description]) => ({ id, name, description })),
}));

export const URGENCIES = [
  { id: "standard", name: "Standard", description: "Within a few days is fine", icon: "calendar" },
  { id: "same-day", name: "Same day", description: "Today if possible", icon: "sun" },
  { id: "express", name: "Express", description: "As soon as you can", icon: "zap" },
  { id: "scheduled", name: "Scheduled", description: "I have a specific time", icon: "clock" },
];
